# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 어서와! 새로운 기술은 언제나 환영이야~
email: root@zzizily.com
description: >- # this means to ignore newlines until "baseurl:"
  안녕하세요 김석영 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.zzizily.com" # the base hostname & protocol for your site, e.g. http://example.com

#social links
# twitter_username: deuxksy
github_username:  deuxksy
rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-include-cache
  - jemoji
  - jekyll-paginate

paginate: 4
paginate_path: posts/page:num/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M"


disqus:
  shortname: tech-zzizily-com


#Enabling Google Analytics
google_analytics: UA-32609745-9

#글 리스트 출력 할때 좀더 보여 주기 안하는게 더 좋아 보임
show_excerpts: false
